export const copy = {
  sidebar: {
    team: "Team",
    workspace: "Workspace",
    home: "Home",
    agents: "Agents",
    store: "Store",
    content: "Content",
    search: "Search",
    reports: "Reports",
    freePlan: "Free plan",
    signOut: "Sign out",
    searchPlaceholder: "Search...",
    inbox: "Inbox",
    myStores: "My stores",
    yourTeams: "Your teams",
    try: "Try",
    connectStore: "Connect store",
    invitePeople: "Invite people",
    whatsNew: "What's new",
    uiRefresh: "UI refresh",
    projects: "Projects",
    views: "Views",
    more: "More",
    personal: "Personal",
    issues: "Issues",
  },
  header: {
    title: "Stores",
    newStore: "New store",
    filter: "Filter",
    display: "Display",
    allStores: "All stores",
    newView: "New view",
  },
  storesTable: {
    columns: {
      name: "Name",
      health: "Health",
      status: "Status",
      products: "Products",
      lastSync: "Last sync",
    },
    empty: "Connect your first store",
    emptyDesc: "Link Shopify, WooCommerce, or other platforms to get started.",
    noUpdates: "No updates",
    onTrack: "On track",
    connectStore: "Connect store",
    runAnalysis: "Run analysis",
    baseUrl: "Store URL",
    baseUrlPlaceholder: "https://your-store.com or store.myshopify.com",
    platform: "Platform",
    platformUrl: "URL",
    platformShopify: "Shopify",
    platformWooCommerce: "WooCommerce",
    analysisRunning: "Analysis running...",
    analysisCompleted: "Completed",
    analysisFailed: "Failed",
    analysisResults: "Results",
    close: "Close",
  },
  content: {
    header: "Content",
    newContent: "New content",
    title: "SEO content creation",
    desc: "Create and optimize content for search. Add meta tags and structured data.",
    metaTitle: "Meta title",
    metaTitlePlaceholder: "Enter meta title for SEO",
    metaDesc: "Meta description",
    metaDescPlaceholder: "Enter meta description",
    empty: "Connect a store to create content for your products.",
  },
  search: {
    header: "Search",
    title: "Search optimization",
    desc: "Optimize content for search and AI discoverability.",
    placeholder: "Search content...",
    empty: "Connect a store to optimize search visibility.",
  },
  home: {
    header: "Home",
    title: "Welcome",
    desc: "Your workspace overview. Get started by connecting a store or exploring the modules.",
  },
  agents: {
    header: "Agents",
    title: "Agents",
    desc: "Manage and configure AI agents for your stores.",
    activityFeed: "Activity",
    noActivity: "No agent activity yet.",
    availableAgents: "Available agents",
  },
  reports: {
    header: "Reports",
    title: "Reports",
    desc: "View analytics and performance reports for your stores.",
    empty: "Connect a store to see reports.",
  },
} as const;
