export const copy = {
  sidebar: {
    team: "Team",
    workspace: "Inbox",
    products: "Products",
    consignors: "Consignors",
    contracts: "Contracts",
    home: "Home",
    agents: "Agents",
    store: "Store",
    content: "Content",
    search: "Search",
    reports: "Reports",
    freePlan: "Free plan",
    signOut: "Sign out",
    searchPlaceholder: "Search...",
    inbox: "Inbox",
    myStores: "My stores",
    yourTeams: "Your teams",
    try: "Try",
    connectStore: "Connect store",
    invitePeople: "Invite people",
    whatsNew: "What's new",
    uiRefresh: "UI refresh",
    projects: "Projects",
    views: "Views",
    more: "More",
    personal: "Personal",
    issues: "Issues",
  },
  header: {
    title: "Stores",
    newStore: "New store",
    filter: "Filter",
    display: "Display",
    allStores: "All stores",
    newView: "New view",
  },
  storesTable: {
    columns: {
      name: "Name",
      health: "Health",
      status: "Status",
      products: "Products",
      lastSync: "Last sync",
    },
    empty: "Connect your first store",
    emptyDesc: "Link Shopify, WooCommerce, or other platforms to get started.",
    noUpdates: "No updates",
    onTrack: "On track",
    connectStore: "Connect store",
    runAnalysis: "Run analysis",
    baseUrl: "Store URL",
    baseUrlPlaceholder: "https://your-store.com or store.myshopify.com",
    platform: "Platform",
    platformUrl: "URL",
    platformShopify: "Shopify",
    platformWooCommerce: "WooCommerce",
    analysisRunning: "Analysis running...",
    analysisCompleted: "Completed",
    analysisFailed: "Failed",
    analysisResults: "Results",
    close: "Close",
  },
  content: {
    header: "Content",
    newContent: "New content",
    title: "SEO content creation",
    desc: "Create and optimize content for search. Add meta tags and structured data.",
    metaTitle: "Meta title",
    metaTitlePlaceholder: "Enter meta title for SEO",
    metaDesc: "Meta description",
    metaDescPlaceholder: "Enter meta description",
    empty: "Connect a store to create content for your products.",
  },
  search: {
    header: "Search",
    title: "Search optimization",
    desc: "Optimize content for search and AI discoverability.",
    placeholder: "Search content...",
    empty: "Connect a store to optimize search visibility.",
  },
  products: {
    title: "Products",
    subtitle: "Consignment listings for your organization.",
    loading: "Loading listings…",
    loadErrorPrefix: "Could not load listings:",
    retry: "Retry",
    emptyHint:
      "No listings yet. Add consignors and contracts in your org, then create listings via the API or a future form.",
    setupTitle: "Get started with consignment",
    setupStepConsignors: "Consignors",
    setupStepConsignorsDesc: "Register people or accounts you accept inventory from.",
    setupStepContracts: "Contracts",
    setupStepContractsDesc: "Agree on splits and terms for each consignor.",
    setupStepListing: "Listings",
    setupStepListingDesc: "Create product rows (SKUs, pricing) tied to a contract—data appears here.",
    colSku: "SKU",
    colTitle: "Title",
    colStatus: "Status",
    colPrice: "Price",
    creating: "Creating…",
    shortcutCreate: "C",
    createFailedPrefix: "Could not create listing:",
    pageHeading: "Products",
    export: "Export",
    import: "Import",
    moreActions: "More actions",
    addProduct: "Add product",
    exportSoon: "Coming soon",
    importSoon: "Coming soon",
    tabAll: "All",
    tabActive: "Active",
    tabDraft: "Draft",
    tabArchived: "Archived",
    tabListLabel: "Product status",
    searchProducts: "Search products",
    toolbarSearchPlaceholder: "Search products, SKUs, titles, and vendors…",
    clearSearch: "Clear search",
    colProduct: "Product",
    colInventory: "Inventory",
    colCategory: "Category",
    colChannels: "Channels",
    categoryUncategorized: "Uncategorized",
    inventoryNotTracked: "Inventory not tracked",
    deleteListing: "Delete",
    deleteListingConfirm: "Delete this listing? This cannot be undone.",
    deleteFailedPrefix: "Could not delete listing:",
    learnMoreProducts: "Learn more about products",
    filterEmptyTitle: "No products match your filters",
    filterEmptyHint: "Try another tab or clear search.",
    emptyHeroTitle: "Your inventory starts here",
    emptyHeroBody:
      "Create drafts, add photos and pricing, and organize listings for consignment. Filter by status and search by title or SKU.",
    emptyHeroHint: "Tip: press C anywhere (outside inputs) to add a product quickly.",
    chipAllListings: "All listings",
    chipActiveListings: "Active",
    chipDraftListings: "Drafts",
    chipArchivedListings: "Archived",
    createModalTitle: "New product",
    createModalClose: "Close",
    createModalTitlePlaceholder: "Product title",
    createModalDescriptionPlaceholder: "Add description…",
    createModalStatusDraft: "Draft",
    createModalStatusPublished: "Published",
    createModalCategoryPlaceholder: "Category",
    createModalCategoryOtherCustom: "Other / custom",
    createModalCategoryPresetApparel: "Apparel",
    createModalCategoryPresetElectronics: "Electronics",
    createModalCategoryPresetHome: "Home",
    createModalCategoryPresetAccessories: "Accessories",
    createModalAddImageTileAria: "Add image",
    createModalDetailsSection: "Details",
    createModalPricePlaceholder: "0.00",
    createModalSkuPlaceholder: "SKU",
    createModalSubmit: "Create product",
    createModalAddImages: "Add images",
    createModalAttachmentAria: "Attach images",
    createModalRemoveImage: "Remove image",
    createModalImageTooLarge: "Each image must be under 5 MB.",
    createModalMaxImages: "You can add up to 8 images.",
    detailBackToProducts: "Back to products",
    detailDesktopOnlyTitle: "Desktop only",
    detailDesktopOnlyBody:
      "This product detail view works on larger screens. Use a desktop browser or widen the window.",
    detailSectionMedia: "Media",
    detailSectionDescription: "Description",
    detailSectionActivity: "Activity",
    detailSidebarHeading: "Properties",
    detailSidebarStatus: "Status",
    detailSidebarPrice: "Price",
    detailSidebarSku: "SKU",
    detailSidebarCategory: "Category",
    detailSidebarVendor: "Vendor",
    detailSidebarChannels: "Channels",
    detailSidebarLabels: "Labels",
    detailLabelsEmpty: "No labels yet.",
    detailAddLabelAria: "Add label",
    detailSidebarRailAria: "Listing metadata",
    detailNoImages: "No images yet.",
    detailMediaAdd: "Add media",
    detailMediaDropHint: "Drop images here",
    detailMediaAddAria: "Add media",
    detailNoDescription: "No description.",
    detailNotFoundTitle: "Listing not found",
    detailNotFoundBody: "This listing may have been deleted or the link is invalid.",
    detailViewProducts: "View products",
    timelineListingCreated: "Listing created",
    timelineLastUpdated: "Last updated",
    timelineCurrentStatus: "Current status",
    detailNone: "—",
  },
  consignorsPage: {
    title: "Consignors",
    body: "Create and manage consignors with POST /api/consignors. Each consignor belongs to your Clerk organization.",
    nextContracts: "Next: Contracts",
    productsLink: "View products",
  },
  contractsPage: {
    title: "Contracts",
    body: "Define contract terms with POST /api/contracts. Link each contract to a consignor before creating listings.",
    prevConsignors: "Back: Consignors",
    productsLink: "View products",
  },
  home: {
    header: "Home",
    title: "Welcome",
    desc: "Your workspace overview. Use Inbox and Products to work consignment listings for your organization.",
  },
  agents: {
    header: "Agents",
    title: "Agents",
    desc: "Manage and configure AI agents for your stores.",
    activityFeed: "Activity",
    noActivity: "No agent activity yet.",
    availableAgents: "Available agents",
  },
  reports: {
    header: "Reports",
    title: "Reports",
    desc: "View analytics and performance reports for your stores.",
    empty: "Connect a store to see reports.",
  },
} as const;
